# -*- coding: utf-8 -*-
"""LVADSUSR89-HarrshaT-IA2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LyhV4nUoJPtKjLMTsDF2fF2sxl45j78-
"""

#Question 1
import numpy as np

def rgb_to_grayscale(rgb_image):
    rgb_image = np.array(rgb_image)
    height, width, _= rgb_image.shape
    grayscale_image = np.zeros((height, width), dtype=np.uint8)
    for y in range(height):
        for x in range(width):
            R, G, B = rgb_image[y, x]
            grayscale_value_FORMULA = 0.2989 * R + 0.5870 * G + 0.1140 * B
            grayscale_image[y, x] = int(grayscale_value_FORMULA)
    return grayscale_image
rgb_image = [[[255,0,0],[0,255,0],[0,0,255],[255,255,0],
              [255,0,255],[0,255,255],[127,127,127],
              [200,200,200],[50,50,50]]]
grayscale_image = rgb_to_grayscale(rgb_image)
print(grayscale_image)

#Question 7
import pandas as pd
import numpy as np
data = {'Name':['Alice','Bob','Charlie','David','Eve','Frank','Grace'],
'Age':[25,30,35,40,45,50,55],
'City':['New York','Los Angeles','Chicago','Houston','Phoenix','Miami','Boston'],
'Department':['HR','IT','Finance','Marketing','Sales','IT','HR']
}
df= pd.DataFrame(data)
print(df)
print("***************Employee Records***************")
#age<45 , not in 'HR', Output: names and cities
wanted_records=df[(df['Age']<45) & (df['Department']!='HR')]
print(wanted_records[['Name','City']])

#Question 8
data = {'Product':['Apples','Bananas','Cherries','Dates',
'Elderberries','Flour','Grapes'],
'Category':['Fruit','Fruit','Fruit','Fruit','Fruit','Bakery','Fruit'],
'Price':[1.20,0.50,3.00,2.50,4.00,1.50,2.00],
'Promotion':[True,False,True,True,False,True,False]
}
df=pd.DataFrame(data)
print(df)
#Fruit category, Promotion false, group by category
result_records = df[(df['Category']=='Fruit') & (df['Promotion']==False)].groupby(df['Category'])

#Question 9

Employee_data = {
	'Employee':['Alice','Bob','Charlie','David'],
	'Department':['HR','IT','Finance','IT'],
	'Manager':['John','Rachel','Emily','Rachel']
}

Project_data = {
		'Employee':['Alice','Charlie','Eve'],
		'Project':['P1','P3','P2']
}

df1 = pd.DataFrame(Employee_data)
df2 = pd.DataFrame(Project_data)
print(df1)
print("*******************************")
print(df2)
print("*******************************")
print(pd.merge(df1,df2,on='Employee',how='left'))

#Question 10
data={
    'Department':['Electronics','Electronics','Clothing','Clothing','Home Goods'],
    'Salesperson':['Alice','Bob','Charlie','David','Eve'],
    'Sales':[70000,50000,30000,40000,60000]
}
df=pd.DataFrame(data)
print(df)
required_records=df['Sales'].groupby(df['Department'])
print(required_records)

#Question 5
data = {
    'StudentID':[1001,1002,1003,1004,1005],
    'Maths':[97,76,86,-1,91],
    'Science':[-1,72,81,60,93],
    'English':[93,72,-1,63,92]
}
df=pd.DataFrame(data).set_index('StudentID')
print(df)

