# -*- coding: utf-8 -*-
"""Python_Internal Assessment -1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EKT-AN_fsnjC2XJJvO2rUXSyQuKbfPTf
"""

#Question 1
area=0
length = int(input("Enter the length of the rectangle (integer):"))
width = int(input("Enter the width of the rectangle (integer):"))
area=length* width
print("Area of the rectangle is: ", area)

#Question 2
weight = float(input("Enter your weight in kilograms: "))
height = float(input("Enter your height in meters: "))
bmi=0
bmi = weight / (height ** 2)
print("Your BMI:", bmi)

#Question 3

student_scores = {}
# Adding student names and scores to the dictionary
student_scores['Harrsha'] = 85
student_scores['Ananya'] = 90
student_scores['Michelle'] = 75
student_scores['Varshaa'] = 95
student_scores['Arvind'] = 80

print("Student Names and their scores:")
for name, score in student_scores.items():
    print(f"{name}: {score}")

#Question 4
age = int(input("Enter your age: "))
if age<18:
  print("user is a minor")
elif age>=18 and age<60:
  print("User is an adult")
elif age>=60:
  print("User is a senior")
else:
  print("Enter correct input")

#Questions 5
#print even numbers from 1 to 50 using a for loop
nos=[]
for i in range(1,51):
  if i%2==0:
    nos.append(i)
  else:
    i+1
print(nos)

#Question 6
password = "xyzabs12_234"
user_pass = input("Enter the password")
while(user_pass!=password):
  print("Enter correct password!")
  break
print("Correct password")

#Question 7
nos = [9, 18, 15, 22]
def cal_average(numbers):
    if not numbers:
        return 0
    return sum(nos) / len(nos)
average = cal_average(nos)
print("Average:", average)

#Question 8
def count_vowels(string):
    vowels = "aAeEiIoOuU"
    count = 0
    for char in string:
        if char in vowels:
            count += 1
    return count

msg = "Good Morning!"
print("Number of vowels:", count_vowels(msg))

#Question 9
import datetime
get_datetime = datetime.datetime.now()
print("Current Date and Time:", get_datetime)

#Question 10
def calculate_addition(num1, num2):
    try:
        result = float(num1) + float(num2)
        return result
    except ValueError:
        return "Error: Both inputs must be numeric."

num1 = input("Enter the first number: ")
num2 = input("Enter the second number: ")

print(calculate_addition(num1, num2))

#Question 11
while True:
    try:
        num = int(input("Please enter an integer: "))
        break
    except ValueError:
        print("Error: Please enter a valid integer.")
print("You entered:", num)

#Question 12
def calculate_division(dividend, divisor):
    try:
        result = dividend / divisor
    except ZeroDivisionError:
        print("Division by zero is not allowed here")
        return None
    return result

res1 = calculate_division(5, 0)
print("Result :", res1)

#Question 13
with open("msg.txt", "w") as file:
    file.write("Hello world!")

# Question 14
with open("msg.txt", "r") as file:
    content = file.read()
print("Content of 'msg.txt':", content)

#Question 15
with open("msg.txt", "a") as file:
    file.write("\nAdded new line to the file msg.txt.")

with open("msg.txt", "r") as file:
    content = file.read()

print("Content of 'msg.txt':\n", content)