# -*- coding: utf-8 -*-
"""LVADSUSR89_harrshat_IA2_lab2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U5oY0QgT1GrAkYM-2v97gO44r4IfIrIL
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

df = pd.read_csv('/content/Mall_Customers.csv')

df.head()



"""# a


"""

df.fillna(df.mean(), inplace=True)

df['Age_Income_Ratio'] = df['Age'] / df['Annual Income (k$)']

scaler = StandardScaler()
scaled_data = scaler.fit_transform(df[['Age', 'Annual Income (k$)', 'Spending Score (1-100)', 'Age_Income_Ratio']])

"""#b

"""

#Elbow and silhouette
inertia_values = []
silhouette_scores = []
k_values = range(2, 10)

for k in k_values:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(scaled_data)
    inertia_values.append(kmeans.inertia_)
    silhouette_scores.append(silhouette_score(scaled_data, kmeans.labels_))

plt.plot(k_values, inertia_values, marker='x')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('Inertia')
plt.title('Elbow Curve for Optimal k value')
plt.xticks(k_values)
plt.show()

plt.plot(k_values, silhouette_scores, marker='x')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('Silhouette Score')
plt.title('Silhouette Scores for Optimal k value')
plt.xticks(k_values)
plt.show()

"""#c

"""

optimal_k = 7
kmeans = KMeans(n_clusters=optimal_k, random_state=42)
kmeans.fit(scaled_data)

cluster_labels = kmeans.predict(scaled_data)

silhouette_avg = silhouette_score(scaled_data, cluster_labels)
print("**********************************SILHOUETTE SCORE*************************\n ",silhouette_avg)

"""#d

"""

df['Cluster'] = kmeans.labels_
cprofiles = df.groupby('Cluster').mean()
print(cprofiles)

"""
### We can target high value products to people in the 32 age group because they have the highest spending score

### To increase the possibility of a customer purchasing a product, we can group the product with appropriate price range which can be promoted to their corresponding age group cluster
"""